"""add llm settings to session

Revision ID: 16c5c95cc108
Revises: d185a0bcef57
Create Date: 2026-02-02 00:18:25.703264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c5c95cc108'
down_revision: Union[str, Sequence[str], None] = 'd185a0bcef57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_history', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('conversation_history_session_id_fkey'), 'conversation_history', type_='foreignkey')
    op.add_column('session', sa.Column('llm_provider', sa.String(), nullable=True))
    op.add_column('session', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'model')
    op.drop_column('session', 'llm_provider')
    op.create_foreign_key(op.f('conversation_history_session_id_fkey'), 'conversation_history', 'session', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.alter_column('conversation_history', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
