"""Update scenario model

Revision ID: 234177d6811c
Revises: 794559eee8e0
Create Date: 2026-03-09 13:23:54.965535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234177d6811c'
down_revision: Union[str, Sequence[str], None] = '794559eee8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('scenario', 'character_gender')
    op.drop_column('scenario', 'industry')
    op.drop_column('scenario', 'scenario_summary')
    op.drop_column('scenario', 'character_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('character_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scenario', sa.Column('scenario_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('scenario', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scenario', sa.Column('character_gender', postgresql.ENUM('MALE', 'FEMALE', name='genderenum'), autoincrement=False, nullable=True))
    op.drop_column('scenario', 'category')
    # ### end Alembic commands ###
