"""Update prompt model

Revision ID: 434fee0ef9a4
Revises: 234177d6811c
Create Date: 2026-03-17 23:39:45.738597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434fee0ef9a4'
down_revision: Union[str, Sequence[str], None] = '234177d6811c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scenario_prompt_id_fkey'), 'scenario', type_='foreignkey')
    op.create_foreign_key(None, 'scenario', 'prompt_template', ['prompt_id'], ['template_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.create_foreign_key(op.f('scenario_prompt_id_fkey'), 'scenario', 'prompt_template', ['prompt_id'], ['template_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
