"""add soft-delete fields to scenarios

Revision ID: 4830b44beec0
Revises: 5eb0b3da51c6
Create Date: 2026-03-05 22:43:35.771428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4830b44beec0'
down_revision: Union[str, Sequence[str], None] = '5eb0b3da51c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable (safe for existing data)
    op.add_column(
        'scenario',
        sa.Column('is_deleted', sa.Boolean(), nullable=True)
    )

    # Step 2: Set default value for all existing rows
    op.execute("UPDATE scenario SET is_deleted = FALSE")

    # Step 3: Make column NOT NULL + set server default for new rows
    op.alter_column(
        'scenario',
        'is_deleted',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_is_deleted'), table_name='scenario')
    op.drop_column('scenario', 'is_deleted')
    # ### end Alembic commands ###
