"""Update prompt model

Revision ID: 794559eee8e0
Revises: d8361fbe8e50
Create Date: 2026-03-09 10:38:55.610806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '794559eee8e0'
down_revision: Union[str, Sequence[str], None] = 'd8361fbe8e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_template', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('prompt_template_created_by_fkey'), 'prompt_template', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_template', 'account', ['created_by'], ['account_id'], ondelete='RESTRICT')
    op.drop_column('prompt_template', 'default_values')
    op.drop_column('prompt_template', 'placeholders')
    op.drop_column('prompt_template', 'output_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_template', sa.Column('output_rule', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('prompt_template', sa.Column('placeholders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('prompt_template', sa.Column('default_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prompt_template', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_template_created_by_fkey'), 'prompt_template', 'account', ['created_by'], ['account_id'])
    op.alter_column('prompt_template', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
