"""add conversation_analysis table

Revision ID: a846bef78ad2
Revises: 16c5c95cc108
Create Date: 2026-02-07 22:27:33.501149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a846bef78ad2'
down_revision: Union[str, Sequence[str], None] = '16c5c95cc108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_analysis',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('conversation_history_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_base64', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_history_id'], ['conversation_history.conversation_history_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_conversation_analysis_analysis_id'), 'conversation_analysis', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_conversation_analysis_conversation_history_id'), 'conversation_analysis', ['conversation_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_analysis_conversation_history_id'), table_name='conversation_analysis')
    op.drop_index(op.f('ix_conversation_analysis_analysis_id'), table_name='conversation_analysis')
    op.drop_table('conversation_analysis')
    # ### end Alembic commands ###
