"""add performance_analysis table

Revision ID: ce0d2356e482
Revises: b7450ba459a6
Create Date: 2026-02-07 22:47:52.998425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0d2356e482'
down_revision: Union[str, Sequence[str], None] = 'b7450ba459a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_performance_evaluation',
    sa.Column('evaluation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('a1_score', sa.Float(), nullable=False),
    sa.Column('a2_score', sa.Float(), nullable=False),
    sa.Column('a3_score', sa.Float(), nullable=False),
    sa.Column('a4_score', sa.Float(), nullable=False),
    sa.Column('a5_score', sa.Float(), nullable=False),
    sa.Column('b6_score', sa.Float(), nullable=False),
    sa.Column('b7_score', sa.Float(), nullable=False),
    sa.Column('b8_score', sa.Float(), nullable=False),
    sa.Column('c9_score', sa.Float(), nullable=False),
    sa.Column('c10_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('rapport_safety', sa.Boolean(), nullable=True),
    sa.Column('context_reinstatement', sa.Boolean(), nullable=True),
    sa.Column('free_recall', sa.Boolean(), nullable=True),
    sa.Column('varied_focused_retrieval', sa.Boolean(), nullable=True),
    sa.Column('closure', sa.Boolean(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('leading_rate', sa.Float(), nullable=True),
    sa.Column('emotion_regulation', sa.Float(), nullable=True),
    sa.Column('active_listening', sa.String(), nullable=False),
    sa.Column('neutral_language', sa.String(), nullable=False),
    sa.Column('contamination_risk', sa.String(), nullable=False),
    sa.Column('pacing_ok', sa.String(), nullable=False),
    sa.Column('trauma_informed', sa.String(), nullable=False),
    sa.Column('question_classifications', sa.JSON(), nullable=True),
    sa.Column('coaching_feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_history.conversation_history_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_ci_performance_evaluation_evaluation_id'), 'ci_performance_evaluation', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ci_performance_evaluation_evaluation_id'), table_name='ci_performance_evaluation')
    op.drop_table('ci_performance_evaluation')
    # ### end Alembic commands ###
