"""initial tables

Revision ID: d185a0bcef57
Revises: 
Create Date: 2026-01-25 23:41:20.710117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd185a0bcef57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STUDENT', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_account_id'), 'account', ['account_id'], unique=False)
    op.create_table('scenario',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('scenario_summary', sa.Text(), nullable=True),
    sa.Column('personal_characteristics', sa.Text(), nullable=True),
    sa.Column('attitude_in_interview', sa.Text(), nullable=True),
    sa.Column('rule_interview', sa.Text(), nullable=True),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('character_gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('times_chosen', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('scenario_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['account.account_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenario_scenario_id'), 'scenario', ['scenario_id'], unique=False)
    op.create_table('session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recording', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_session_id'), 'session', ['session_id'], unique=False)
    op.create_table('conversation_history',
    sa.Column('conversation_history_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_history_id')
    )
    op.create_index(op.f('ix_conversation_history_conversation_history_id'), 'conversation_history', ['conversation_history_id'], unique=False)
    op.create_table('note',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('note_content', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_note_note_id'), 'note', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_note_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_conversation_history_conversation_history_id'), table_name='conversation_history')
    op.drop_table('conversation_history')
    op.drop_index(op.f('ix_session_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_scenario_scenario_id'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_account_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
