"""Add output_rule

Revision ID: d8361fbe8e50
Revises: 31b876598103
Create Date: 2026-03-06 13:29:15.180370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8361fbe8e50'
down_revision: Union[str, Sequence[str], None] = '31b876598103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_template', sa.Column('output_rule', sa.Text(), nullable=True))
    op.drop_column('prompt_template', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_template', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('prompt_template', 'output_rule')
    # ### end Alembic commands ###
