"""Add prompt model

Revision ID: e71b074d8eb5
Revises: 5eb0b3da51c6
Create Date: 2026-03-05 22:43:41.723957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71b074d8eb5'
down_revision: Union[str, Sequence[str], None] = '5eb0b3da51c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_template',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('default_values', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index(op.f('ix_prompt_template_template_id'), 'prompt_template', ['template_id'], unique=False)
    op.add_column('scenario', sa.Column('prompt_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scenario', 'prompt_template', ['prompt_id'], ['template_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'prompt_id')
    op.drop_index(op.f('ix_prompt_template_template_id'), table_name='prompt_template')
    op.drop_table('prompt_template')
    # ### end Alembic commands ###
